name: Package Extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUBWORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependacies
        run: npm install

      - name: Build Compass into an Extension
        run: |
              npm run build
              runTimestamp="$(date +%D)_$(date +%H)-$(date +%M)-$(date +%S)"
              mkdir -p extension/builds/
              mv dist/* extension/builds/
              cp -r extension/base/* extension/builds/
      
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Find and Replace Absolute Directories
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          # A regular expression of files to include in our find and replace
          include: extension/builds/ntp.js
          # A regular expression of files to exclude in our find and replace
          exclude: .git
          # The string we want to replace
          find: /bac
          # The new string to replace with
          replace: ./bac
      - name: Make CRX
        # You may pin to the exact commit or the version.
        # uses: cardinalby/webext-buildtools-chrome-crx-action@6ffc20d012116ea3fa0c6697382b026fc7df9535
        uses: cardinalby/webext-buildtools-chrome-crx-action@2.0.0
        with:
            # Path to WebExtension directory
            zipFilePath: ./extension/builds/
            # Path to save result crx file
            crxFilePath: ./extension/
            # Contents of private key used to sign crx file
            privateKey: ${{ secrets.CHROME_SIGNING_KEY }}
            # Path to save update.xml file for extensions hosted not on Chrome Web Store. This xml is used as response at url, specified in manifest's `update_url` key file
            updateXmlPath: ./extension/
            # Required, if you specified updateXmlPath. URL to the .crx file
            updateXmlCodebaseUrl: ./extension/*.crx
      - name: Return .zip
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.time.outputs.time }}
          path: ./extension/builds/
      - name: Return .crx
        uses: actions/upload-artifact@v2
        with:
          name: Chrome-Extension_${{ steps.time.outputs.time }}
          path: ./extension/builds/
